### ISSUE TITLE
标题没有h1的话报错

### ISSUE THREAD

**Issue by xsbreakaway** [zq99299/gitbook-plugin-anchor-navigation-ex#1]
标题没有h1的话报错TypeError: Cannot read property 'children' of undefined
有h1、h3,没有h2也会报错

**Comment by zq99299** [comment]
嗯。 好的。
有空。把这个逻辑修改下。 不过在什么情况下。你会这样排版。正常情况下一个文件都有一个h1. 然后往下

**Comment by zq99299** [comment]
ok了。 现在已经修复了。 如果没有按照 1.2.3 1.2.3 类似的层级。从2开始的话。会直接忽略的。
