### ISSUE TITLE
V1.0.x 忽略在指定页面生成导航

### ISSUE THREAD

**Issue by zq99299** [zq99299/gitbook-plugin-anchor-navigation-ex#15]
在某些情况下，是不需要生成的，比如介绍页。有可能有这个需求

**Comment by NewFuture** [comment]
两种方案 ：
* 通过 metadata 标注
* 特定html注释

第一种方案,在markdown 的开头
```markdown
---
notoc: true
---
```
可以通过 `page.notoc`判断

第二种方案 类似与 [markdown-toc](https://github.com/jonschlinkert/markdown-toc/blob/master/index.js#L61)
```markdown
<!-- notoc -->
```
可以通过`/<!--[ \t]*notoc[ \t]*-->/.test(page.content);`判断


也可以两种方案都用上

**Comment by zq99299** [comment]
en .  好的我试试。 一直不知道怎么取到这个标记呢。

**Comment by NewFuture** [comment]
另外，这个问题，
当页面只有一个标题的时候，也没有必要显示那个目录

**Comment by zq99299** [comment]
嗯。 貌似是的。 这个倒是可以优化下

**Comment by NewFuture** [comment]
PR 了 #21

**Comment by zq99299** [comment]
已解决v1.0.4
