### ISSUE TITLE
页内顶部截图展示(mode: "pageTop") 能否只在某些页面显示

### ISSUE THREAD

**Issue by vikyd** [zq99299/gitbook-plugin-anchor-navigation-ex#17]
页内顶部截图展示(mode: "pageTop") 能否只在某些页面显示

**Comment by zq99299** [comment]
#15  这个目前我还没有找到解决方案。如果找到后，才能有其他更多的想法扩展

我明白你想要的效果，但是这个效果貌似和其他的一些 toc的插件类似了。目前会不支持这个想法。暂时还没有想到怎么让这个效果替代掉整体的一个导航。 如果你也是一个开发人员，可以共同讨论

**Comment by vikyd** [comment]
试了下这个插件 https://github.com/whzhyh/gitbook-plugin-toc ， 能解决我的问题，即在需要的页面添加`<!-- toc -->`即可。但这个插件的问题是生成的 toc 与 gitbook-plugin-anchor-navigation-ex 的标题 id 不一致，若能一致，我觉得问题就解决了。

**Comment by zq99299** [comment]
那如果这样的话。我来梳理一下功能：
mode: "float" 浮动导航
mode: "pageTop" 页面内部顶部导航
上面两种模式是互斥的。且是全部页面添加

现在你这种，那我的理解应该是：
mode: "float" 浮动导航 的情况下，再自行选择是否在顶部显示toc吧？

这种想法我有想做的计划。非常感谢你能提供其他的插件供我参考。等项目不忙的时候我会开发这个功能

**Comment by vikyd** [comment]
对！
就是`mode: "float" 浮动导航 的情况下，再自行选择是否在顶部显示toc`。

**Comment by zq99299** [comment]
哈哈。我也想要这个功能。等不忙的时候，再来开发

**Comment by zq99299** [comment]
你看看。已经增加了。暂时的解决方案是在页面中增加 `<extoc></extoc>` 标签，就会显示mode: "pageTop" 一样的目录了

**Comment by zq99299** [comment]
版本是：1.0.3。

其他的样式和操作什么的。就只有真的等 项目忙完后再来优化了
