### ISSUE TITLE
覆盖已经设置过的锚点链接(#ID)

### ISSUE THREAD

**Issue by NewFuture** [zq99299/gitbook-plugin-anchor-navigation-ex#18]
gitbook 可以使用 (参照gitbook文档 https://toolchain.gitbook.com/syntax/markdown.html#headings )
如
```markdown
## 标题1 {#title}
```
gitbook 会使用 `titile` 作为这个标题的ID

使用 插件时，生成的ID是 `1-1-标题1`这样的 覆盖 `title` 
这个时候一些链接就失效和不可控了 😂

**Comment by zq99299** [comment]
没有明白。你的意思是啥？ 本插件重写标题ID的原因是： 防止标题重复，导致锚点导航失效。

**Comment by NewFuture** [comment]
就是如果已经设置标题了，就保留这个标题不修改。这样随着文档的删改锚点永远是固定的(否则可能导致链接失效)

如果自动添加的标题加上这个重写机制很棒 😸

**Comment by NewFuture** [comment]
正在 review  代码，发现这个地方 https://github.com/zq99299/gitbook-plugin-anchor-navigation-ex/blob/master/assets/lib/plugin.js#L39 

是不是有个BUG，三级标题以后的还是可能会重复?

**Comment by zq99299** [comment]
哦。 你的意思是 分享出去的标题的锚点链接吗？ 我在家里，链接git等网站特别慢

**Comment by zq99299** [comment]
嗯。 看到了。h3以后的标题还是可能重复。 当时没有考虑到这个问题。
在使用的时候，有人说在生成的导航链接中，有重复的id，导致链接失效。当时就解决了 h1-h3 的问题。

那个固定标题的貌似没有想到一个好的解决方案

**Comment by NewFuture** [comment]
嗯，还有内联的定位锚点都会失效。

哈哈,端午节快乐 😃

**Comment by zq99299** [comment]
哈哈哈哈 。同乐同乐。 你有啥好的解决方案不

**Comment by NewFuture** [comment]
把每个页面所有ID进行 hash 计数。出现了重复的就后缀(或者前缀)递增

**Comment by zq99299** [comment]
还有一个标题重写呢。这个是不是会和hashid重复

**Comment by NewFuture** [comment]
把重写的都存下来就不会重复了 
改一下这个函数
```js
/**
 * 处理锚点
 * @param header
 * @returns {*}
 */
function addId(header, hashmap) {
    var id = header.attr('id') || slug(header.text());
    var n = hashmap[id] || 0;
    hashmap[id] = n + 1;
    if (n) {
        id = id + '__' + n;
        hashmap[id] = 1;
    }
    header.attr("id", id);
    return id;
}
```
调用一次，后面的二次重写都去掉即可
#6 这个问题也解决了

**Comment by NewFuture** [comment]
但是这个例子
```
## 获取实例

## 成绩统计
### 方法
### 功能
### 参数
### 返回值

## 历年成绩
### 方法
### 功能
### 参数
### 返回值
```
会变成这种

```
...
方法
功能
...
方法__1
功能__1
```

在不重复的时候链接会更好看

**Comment by zq99299** [comment]
那你的意思就是说：标题 和 id 分开了。

**Comment by NewFuture** [comment]
是这个意思，这样完整点儿
```
## hh1               ==> #hh1

## hh1 {#id1}        ==> #id1 //指定ID
### hhh1 {#id2}      ==> #id2
### hhh2             ==> #hhh2

## hh1               ==> #hh1__1 
### hhh1             ==> #hhh1  //重复但是ID未占用
### hhh2             ==> #hhh2__1 //重复且ID使用过一次
### hhh2             ==> #hhh2__2 //重复且ID使用过2次
```

**Comment by zq99299** [comment]
en . 可以这样做。 标题和 id 就分开好了

**Comment by zq99299** [comment]
你现在这样是没有重写后的标题。 如果重写标题（不是重写id）;这种情况需要和id相关联嘛?如果关联了。修改了标题的层级那么id也就变了
```
# hh1
## hh11

重写后的标题：
1. hh1
1.1.hh11
```

**Comment by NewFuture** [comment]
id重写发生在文本重写之前，所以不会影响

**Comment by zq99299** [comment]
那就是把重写后的标题 与 id分离了。 这样也可以

**Comment by NewFuture** [comment]
PR #19 
顺便删了一下不必要的重复操作，速度快了不少
