### ISSUE TITLE
去掉h1的标号

### ISSUE THREAD

**Issue by NewFuture** [zq99299/gitbook-plugin-anchor-navigation-ex#20]
正常情况一般一个页面只存在一个h1
所以所有标题前面都显示一个 1.x 会变得很尴尬

这一层的是不是去掉比较合适，或者加个配置隐藏掉？

**Comment by zq99299** [comment]
一个或多个h1标题的话。 这个没有定论。 小型文章的话。有可能有多个。大型文章的话，就会拆分得很细。

**Comment by NewFuture** [comment]
这样我觉得有必要给一个隐藏`H1`的level的选项

**Comment by zq99299** [comment]
这个 我在想是否给一个配置，如果是定位成大型书籍，一个页面只有一个h1标签的话。 #24 这个里面的效果要好于现在的

**Comment by OliverYGM** [comment]
实际使用中 确实有 去掉h1的标号 的需求

**Comment by zq99299** [comment]
@OliverYGM  嗯。 有，但是处理起来有问题。 如果一个页面只有一个h1的话。 去掉后面的.1 这个是没有问题的。 如果是多个的话。就有问题了。还没想好如何弄

**Comment by zq99299** [comment]
V1.0.6中新增去除的选项。
