### ISSUE TITLE
生成PDF和电子书的时候隐藏toc

### ISSUE THREAD

**Issue by NewFuture** [zq99299/gitbook-plugin-anchor-navigation-ex#23]
导出PDF版的时候能否去掉？

**Comment by zq99299** [comment]
这个倒是困扰过我。

怎么能知道是在生成pdf呢？ 有什么实现方案吗?

**Comment by NewFuture** [comment]
1个是特定css 参考这个https://github.com/GitbookIO/theme-default/blob/master/src/less/ebook/base.less#L19
另一个是打印样式`@print`
你可以试一下，我现在没有环境

**Comment by zq99299** [comment]
感觉好复杂的样子

**Comment by zq99299** [comment]
close
