### ISSUE TITLE
使用hbook时该插件不生效

### ISSUE THREAD

**Issue by chunhuajiang** [zq99299/gitbook-plugin-anchor-navigation-ex#28]
有个哥们基于gitbook开发了一个主题/工具 [hbook](https://github.com/simonguo/hbook)，但是安装好本插件后，我使用`hbook build`将markdown文件生成html后，发现本插件不工作，估计是你们哪里有冲突了？想请问怎么解决？

我在hbook那里也提了一个issue https://github.com/simonguo/hbook/issues/2

鱼我所欲也，熊掌亦我所欲也，不会前端，所以不得不做伸手党~

**Comment by zq99299** [comment]
哥们， 怎么个不能工作法？  

我这个插件  是按默认主题的css来生成的。 其他的定制的css 可能会一部分不正常。 你有线上的地址 让我访问看看吗

**Comment by zq99299** [comment]
https://github.com/zhangjikai/gitbook-use/blob/master/book.json   这个哥们里面用的还是低版本的 插件。

我估计还是和 第三方主题有关系吧

**Comment by chunhuajiang** [comment]
- 不能工作的具体表现是，页面上导航的图标都不显示~
- 是多个book合并在一起的，gitbook.com没法一起解析，所以我的内容都还在本地，囧~
- 我把插件更新到最新版了，效果一样的。
- 应该是与第三方的主题有关，因为我今天下午在gitbook的官方文档上看到有说如果采用第三方主题，某些插件可能不能正常工作

谢谢你的响应，我先再琢磨琢磨~
