### ISSUE TITLE
安装插件，build后没有效果

### ISSUE THREAD

**Issue by fujunchun** [zq99299/gitbook-plugin-anchor-navigation-ex#30]
安装插件，编译文档后无效，不能使用
gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3

**Comment by zq99299** [comment]
无效果是什么改变都没有吗？还是？
你怎么配置的呢？方便提供下书籍的链接吗

**Comment by fujunchun** [comment]
我用gitbook-cli 本地编译的，出现问题，在gitbook.com上没有问题
gitbook 版本信息
gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3

**Comment by zq99299** [comment]
我怀疑你本地文件有问题。 你尝试下 把 node_modules 删除掉，install 后，再尝试下

**Comment by zq99299** [comment]
构建后，还有一个是不是浏览器的缓存问题 CTRL + f5 强制刷新浏览器也试试

**Comment by fujunchun** [comment]
非常感谢，你说的重新install 和清缓存同时用了，本地构建可以了

**Comment by zq99299** [comment]
好的。
