### ISSUE TITLE
自动编号和出现在TOC中的章节是否可以扩展到至少H6？

### ISSUE THREAD

**Issue by lAndRaxeE** [zq99299/gitbook-plugin-anchor-navigation-ex#31]
目前只能编号h1-h3，如果使用了"multipleH1": false，那么实际就只有h2-h3了，只能有两层目录，显得有些少了

**Comment by zq99299** [comment]
是这样的。 扩展到6的话。 提取的就太多了。  我看了很多书籍，这种目录一样的导航都不会太深。 如果太深，那么是文章组织得有问题；
