### ISSUE TITLE
支持最新版本的gitbook吗？

### ISSUE THREAD

**Issue by succeed0924** [zq99299/gitbook-plugin-anchor-navigation-ex#32]
我通过3.2.3版本的配置了插件，但是没办法生效，求解答~

**Comment by zq99299** [comment]
把你的配置贴一下，我也是3.2.3的 @succeed0924

**Comment by succeed0924** [comment]
{
   "plugins": [
        "theme-default",
        "anchor-navigation-ex"
    ],
   "pluginsConfig": {
      "theme-default": {
           "showLevel": true
      }
   }
}
上面是最后改成的状态。
我也有加下面的配置：
{
    "showLevel": true,
    "associatedWithSummary": true,
    "printLog": false,
    "multipleH1": true,
    "mode": "float",
    "float": {
        "showLevelIcon": false,
        "level1Icon": "fa fa-hand-o-right",
        "level2Icon": "fa fa-hand-o-right",
        "level3Icon": "fa fa-hand-o-right"
    },
    "pageTop": {
        "showLevelIcon": false,
        "level1Icon": "fa fa-hand-o-right",
        "level2Icon": "fa fa-hand-o-right",
        "level3Icon": "fa fa-hand-o-right"
    }
}

是还有其他的配置没加吗？

**Comment by zq99299** [comment]
配置看着是没有 什么问题； 你的书籍在github么。 我去下载下来看看

**Comment by succeed0924** [comment]
这个倒没有，我在本地操作的。就是按照示例里的 h1-h3 这样写了很多个，然后里面随便写了一点字。

**Comment by zq99299** [comment]
本地的话 要gitbook server 才能看到效果

**Comment by succeed0924** [comment]
嗯，就是执行serve 打开页面没有生效所以才来请教的！

**Comment by zq99299** [comment]
```javascript
{
  "title": "essay-note",
  "description": "随笔记未分类，也就是大杂烩的一本笔记",
  "language": "zh-hans",
   "plugins": [
      "splitter",
      "-github",
      "prism",
      "-highlight",
      "expandable-chapters",
      "page-footer-ex",
      "anchor-navigation-ex",
      "advanced-emoji"
    ],
  "pluginsConfig": {
    "prism": {
       "css": [
         "prismjs/themes/prism-okaidia.css"
       ]
    },
    "anchor-navigation-ex":{
       "multipleH1":false
    },
    "theme-default": {
       "showLevel": true
    }
  }
} 
```

这是我的配置。 你参考下。 是不是你用了其他的什么插件 冲突了？

**Comment by succeed0924** [comment]
好的，我试一下，多谢！成功了我再反馈问题的原因。

**Comment by zq99299** [comment]
https://github.com/zq99299/gitbook-guide  这里是我写教程的那本书籍。 你可以把这个下载下来看看 运行看看是否有效果

**Comment by succeed0924** [comment]
我刚尝试了一下全新的gitbook安装插件是正常的，但是我之前那个依旧无法找出问题，我尝试uninstall了所有插件，依旧存在问题，后面复制了正常的 node_moudules文件夹才正常，文件夹内容如下：
之前有错误的node_modules：
.bin
cheerio
colors
core-util-is
CSSselect
CSSwhat
dom-serializer
domelementtype
domhandler
domutils
entities
gitbook-plugin-anchor-navigation-ex
github-slugid
htmlparser2
inherits
isarray
lodash
readable-stream
string_decoder



正确的node_modules：
.bin
boolbase
cheerio
clipboard
colors
core-util-is
css-select
css-what
delegate
dom-serializer
domelementtype
domhandler
domutils
emojify.js
entities
gitbook-plugin-advanced-emoji
gitbook-plugin-anchor-navigation-ex
gitbook-plugin-bootstrap-callout
gitbook-plugin-expandable-chapters
gitbook-plugin-github
gitbook-plugin-page-footer-ex
gitbook-plugin-prism
gitbook-plugin-splitter
github-slugid
good-listener
htmlparser2
inherits
isarray
lodash
lodash.assignin
lodash.bind
lodash.defaults
lodash.filter
lodash.flatten
lodash.foreach
lodash.map
lodash.merge
lodash.pick
lodash.reduce
lodash.reject
lodash.some
minimist
mkdirp
moment
nth-check
prismjs
process-nextick-args
readable-stream
safe-buffer
select
string_decoder
tiny-emitter
util-deprecate

**Comment by succeed0924** [comment]
不知道为什么对比起来之前的会缺少这么多东西！不过问题也算是解决了，多谢！

**Comment by zq99299** [comment]
直接暴力删除node_modules文件夹，然后gitbook install 就好了。

**Comment by xiaqunfeng** [comment]
同样遇到这个问题，采用方法：“暴力删除node_modules文件夹，然后gitbook install”，依然没有显示效果
我安装显示的版本：
├─┬ gitbook-plugin-anchor-navigation-ex@1.0.14
│ ├── colors@1.3.3                                                                                                                 buffers
│ └── github-slugid@1.0.1
├── gitbook-plugin-book-summary-scroll-position-saver@0.0.7
├── gitbook-plugin-code@0.1.0
├── gitbook-plugin-copy-code-button@0.0.2
├── gitbook-plugin-disqus@0.1.0
├── gitbook-plugin-donate@1.0.2
├── gitbook-plugin-mathjax@1.1.2
├── gitbook-plugin-multipart@0.3.0
├── gitbook-plugin-search-pro@2.0.2
├── gitbook-plugin-splitter@0.0.8
├── gitbook-plugin-theme-comscore@0.0.3
└── gitbook-plugin-toggle-chapters@0.0.3
我的配置：
      "anchor-navigation-ex": {
        "associatedWithSummary": true,
        "showLevel": false,
        "multipleH1": false,
        "mode": "float",
        "showGoTop": true,
        "showLevel": true,
        "float": {
            "floatIcon": "fa fa-navicon",
            "showLevelIcon": true,
            "level1Icon": "fa fa-hand-o-right",
            "level2Icon": "fa fa-hand-o-right",
            "level3Icon": "fa fa-hand-o-right"
        }
      }
试了很久，一直没发现问题，哭

**Comment by zq99299** [comment]
@xiaqunfeng 你的书籍项目在 github 上面吗？

**Comment by xiaqunfeng** [comment]
> @xiaqunfeng 你的书籍项目在 github 上面吗？
已解决：
1、删除本地node_modules文件夹
2、复制你的项目 https://github.com/zq99299/gitbook-guide 下的node_modules文件夹过来
3、执行gitbook install 安装即可
猜测：
你的node_modules里有其他依赖项，在直接install的时候并没有安装

**Comment by zq99299** [comment]
这方法是不正常的解决方案，你把你书籍地址给我帮你看看是咋回事。没有见过其他人反应这个情况

**Comment by xiaqunfeng** [comment]
> 这方法是不正常的解决方案，你把你书籍地址给我帮你看看是咋回事。没有见过其他人反应这个情况

那麻烦了，地址如下：
https://github.com/xiaqunfeng/tec-point

**Comment by zq99299** [comment]
@xiaqunfeng  
首先把 "anchor-navigation-ex", 移动到最上面尝试看看，如果还不行，那么你添加的插件有和本插件冲突的，需要你自己一个一个排除尝试； 同样为了 install 安装的干净，需要 install 之前删除下 node_modules 文件夹

```
    "plugins": [
		"anchor-navigation-ex",
        "multipart",
        "disqus",
        "code",
        "mathjax",
        "splitter",
        "toggle-chapters",
        "copy-code-button",
        "-theme-comscore",
        "donate",
        "book-summary-scroll-position-saver",
        "-lunr", "-search", "search-pro"
    ],
```
我在我本地测试能出来效果，这可见一定是某个插件和本插件冲突了， 如果找不出来 其中某一个插件的功能肯定是缺失的。

**Comment by xiaqunfeng** [comment]
@zq99299 
非常感谢🌹，按照你说的，我把 anchor-navigation-ex 放到第一行，删除node_modules 文件夹，重新install后效果出来了。
应该是插件冲突了，不过其他插件的效果暂时没受到影响。
后续如果发现了具体是哪个插件影响了本插件，再来提issue。

**Comment by lijialalala** [comment]
我也遇到没生效的问题：

**Comment by lijialalala** [comment]
我也遇到没生效的问题，可以麻烦看看吗~

**Comment by psycholali** [comment]
我也遇到multipleH1: false没生效的问题，可以麻烦看看吗~
{
  "author": "xx",
  "description": "xx",
  "extension": null,
  "generator": "site",
  "isbn": "",
  "links": {
      "sharing": {
          "all": "",
          "facebook": null,
          "google": null,
          "twitter": null,
          "weibo": null
      },
      "sidebar": {}
  },
  "output": null,
  "pdf": {
      "fontSize": 12,
      "footerTemplate": null,
      "headerTemplate": null,
      "margin": {
          "bottom": 36,
          "left": 62,
          "right": 62,
          "top": 36
      },
      "pageNumbers": false,
      "paperSize": "a4"
  },
  "plugins": [
    "anchor-navigation-ex",
    "-lunr", 
    "-search", 
    "search-plus",
    "tbfed-pagefooter",
    "expandable-chapters",
    "prism"
  ],
  "pluginsConfig": {
    "tbfed-pagefooter": {
      "copyright":"&copy xxx",
      "modify_label": "文件修订时间：",
      "modify_format": "YYYY-MM-DD HH:mm:ss"
    },
    "anchor-navigation-ex":{
      "multipleH1": false
   },
    "theme-default": {
      "showLevel": true
    },
    "prism": {
      "css": [
        "prismjs/themes/prism-okaidia.css"
      ]
   }
  },
  "title": "Node GitBook",
  "variables": {}
  
}

**Comment by zq99299** [comment]
看你配置应该没有什么问题，你的书籍在 github 上吗？ 我拉下来看看

**Comment by zq99299** [comment]
直接暴力删除node_modules文件夹，然后gitbook install ，试过没

**Comment by psycholali** [comment]
> 直接暴力删除node_modules文件夹，然后gitbook install ，试过没

试过，还是没生效呢~ 我简单写了一个例子，可以帮忙看看吗？在这个里面的gitbook2文件夹下
https://github.com/lijialalala/md/

**Comment by zq99299** [comment]
文件不全。没有文档， 你检查下看看。 哪些 a.md  b.md  没有上传

**Comment by zq99299** [comment]
根据你提供的例子，我正常 gitbook install, 之后没有修改其他的配置（除了下面的提到的两个外），功能正常

a.md 
```
# ssss

## xxxxx

### cc

## aaa
```

配置调整
```
    "anchor-navigation-ex":{
      "multipleH1": false
   },
    "theme-default": {
      "showLevel": false
    }
```
显示如下：

```
ssss
1. xxxxx
1.1. cc
2. aaa
```

如果配置为  true
```
    "anchor-navigation-ex":{
      "multipleH1": true
   },
    "theme-default": {
      "showLevel": false
    }
```

显示如下

```
1. ssss       <--- 看这里，证明   "multipleH1":  切换功能正常
1.1. xxxxx
1.1.1. cc
1.2. aaa
```

总结：

1.  你可能对 multipleH1 功能不理解
2.   "showLevel": true  有可能打开了序号，看错了，

当   "showLevel": true 并且  associatedwithsummary=true （默认为 true） 的时候,会吧侧边栏序号添加到标题前面

下面是详细配置，你参考参考：https://github.com/zq99299/gitbook-plugin-anchor-navigation-ex/blob/master/doc/config.md#associatedwithsummary--typeboolean

**Comment by psycholali** [comment]
谢谢，是我理解错了。我以为这个issue是关于减少左侧导航的序号的优化，原来是减少md文章标题序号的优化。请问左侧导航序号可以减少一个层级吗？比如说第一个就是1. 而不是1.1

**Comment by zq99299** [comment]
我记得以前官网有个专门说这个序号的问题，官网坚持不会修改这个提议的。所以要么自己手动排序，要么就忍受
