### ISSUE TITLE
回到顶部的按钮点击无效。

### ISSUE THREAD

**Issue by kumakumasan** [zq99299/gitbook-plugin-anchor-navigation-ex#42]
我的插件配置情形如下，请问到底是不是有插件冲突造成的？还是需要对文章进行特殊处理？

{
    "title": "xxx",
    "author": "xx",
    "language": "zh-hans",
    "plugins": [
      "-lunr", 
	  "-fontsettings",
	  "-search", 
	  "-sharing",
	  "search-pro",
	  "expandable-chapters",
	  "splitter",
	  "lightbox",
	  "hide-element",
	  "anchor-navigation-ex",
	  "tbfed-pagefooter",
	  "-theme-fexa",
	  "-back-to-top-button",
	  "flexible-alerts",
	  "copy-code-button"
    ],
	"variables": {
		"themeFexa":{
            "nav":[
                {
                    "url":"http://...",
                    "target":"_blank",
                    "name": ""
                }
            ]
        }
	},
    "pluginsConfig": {
        "hide-element": {
            "elements": [".gitbook-link"]
        },
		"tbfed-pagefooter": {
            "copyright":"Copyright doc.brucex.info",
            "modify_label": "该文件最后修改时间：",
            "modify_format": "YYYY-MM-DD HH:mm:ss"
        },
		"anchor-navigation-ex": {
            "showLevel": true,
			"associatedWithSummary": false,
			"printLog": false,
			"multipleH1": true,
			"mode": "float",
			"showGoTop":true
        },
		"theme-fexa":{
            "search-placeholder":"输入关键字搜索",
			"logo":"./assets/logo.png",
            "favicon": "./assets/favicon.ico"
        },
		"flexible-alerts": {
		  "note": {
			"label": "说明"
		  },
		  "tip": {
			"label": "提示"
		  },
		  "warning": {
			"label": "注意"
		  },
		  "danger": {
			"label": "警告"
		  }
		}
    }
}

**Comment by kumakumasan** [comment]
f12调试模式看点击这个按钮是报错；
```
Uncaught Error: Syntax error, unrecognized expression: #
    at Function.t.error (theme.js:1)
    at t.tokenize (theme.js:2)
    at Function.t [as find] (theme.js:1)
    at de.fn.init.find (theme.js:2)
    at i (theme.js:4)
    at o (theme.js:4)
    at p (theme.js:4)
    at HTMLAnchorElement.v (theme.js:4)
    at HTMLDocument.dispatch (theme.js:2)
    at HTMLDocument.m.handle (theme.js:2)
```

**Comment by zq99299** [comment]
你，这插件貌似用的有点杂啊，不排除是插件冲突，清空你的 nodmodus 试试，之前用了另外一个 回到顶部的插件了吧



---原始邮件---
发件人: "kumakumasan"<notifications@github.com&gt;
发送时间: 2019年11月3日(星期日) 上午10:57
收件人: "zq99299/gitbook-plugin-anchor-navigation-ex"<gitbook-plugin-anchor-navigation-ex@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zq99299/gitbook-plugin-anchor-navigation-ex] 回到顶部的按钮点击无效。 (#42)



我的插件配置情形如下，请问到底是不是有插件冲突造成的？还是需要对文章进行特殊处理？
 
{
 "title": "xxx",
 "author": "xx",
 "language": "zh-hans",
 "plugins": [
 "-lunr",
 "-fontsettings",
 "-search",
 "-sharing",
 "search-pro",
 "expandable-chapters",
 "splitter",
 "lightbox",
 "hide-element",
 "anchor-navigation-ex",
 "tbfed-pagefooter",
 "-theme-fexa",
 "-back-to-top-button",
 "flexible-alerts",
 "copy-code-button"
 ],
 "variables": {
 "themeFexa":{
 "nav":[
 {
 "url":"http://...",
 "target":"_blank",
 "name": ""
 }
 ]
 }
 },
 "pluginsConfig": {
 "hide-element": {
 "elements": [".gitbook-link"]
 },
 "tbfed-pagefooter": {
 "copyright":"Copyright doc.brucex.info",
 "modify_label": "该文件最后修改时间：",
 "modify_format": "YYYY-MM-DD HH:mm:ss"
 },
 "anchor-navigation-ex": {
 "showLevel": true,
 "associatedWithSummary": false,
 "printLog": false,
 "multipleH1": true,
 "mode": "float",
 "showGoTop":true
 },
 "theme-fexa":{
 "search-placeholder":"输入关键字搜索",
 "logo":"./assets/logo.png",
 "favicon": "./assets/favicon.ico"
 },
 "flexible-alerts": {
 "note": {
 "label": "说明"
 },
 "tip": {
 "label": "提示"
 },
 "warning": {
 "label": "注意"
 },
 "danger": {
 "label": "警告"
 }
 }
 }
 }

**Comment by zq99299** [comment]
还有就是，吧插件顺序上调，如果还不正常那就是冲突了



---原始邮件---
发件人: "kumakumasan"<notifications@github.com&gt;
发送时间: 2019年11月3日(星期日) 上午10:57
收件人: "zq99299/gitbook-plugin-anchor-navigation-ex"<gitbook-plugin-anchor-navigation-ex@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zq99299/gitbook-plugin-anchor-navigation-ex] 回到顶部的按钮点击无效。 (#42)



我的插件配置情形如下，请问到底是不是有插件冲突造成的？还是需要对文章进行特殊处理？
 
{
 "title": "xxx",
 "author": "xx",
 "language": "zh-hans",
 "plugins": [
 "-lunr",
 "-fontsettings",
 "-search",
 "-sharing",
 "search-pro",
 "expandable-chapters",
 "splitter",
 "lightbox",
 "hide-element",
 "anchor-navigation-ex",
 "tbfed-pagefooter",
 "-theme-fexa",
 "-back-to-top-button",
 "flexible-alerts",
 "copy-code-button"
 ],
 "variables": {
 "themeFexa":{
 "nav":[
 {
 "url":"http://...",
 "target":"_blank",
 "name": ""
 }
 ]
 }
 },
 "pluginsConfig": {
 "hide-element": {
 "elements": [".gitbook-link"]
 },
 "tbfed-pagefooter": {
 "copyright":"Copyright doc.brucex.info",
 "modify_label": "该文件最后修改时间：",
 "modify_format": "YYYY-MM-DD HH:mm:ss"
 },
 "anchor-navigation-ex": {
 "showLevel": true,
 "associatedWithSummary": false,
 "printLog": false,
 "multipleH1": true,
 "mode": "float",
 "showGoTop":true
 },
 "theme-fexa":{
 "search-placeholder":"输入关键字搜索",
 "logo":"./assets/logo.png",
 "favicon": "./assets/favicon.ico"
 },
 "flexible-alerts": {
 "note": {
 "label": "说明"
 },
 "tip": {
 "label": "提示"
 },
 "warning": {
 "label": "注意"
 },
 "danger": {
 "label": "警告"
 }
 }
 }
 }

**Comment by zq99299** [comment]
刚看源码确认了下，本插件的回到顶部按钮无 js 操作，所以如果无效，那么很有可能是浮动导航的内容被其他插件给修改了，导致回不去了；

你现在可以做的：
1. 清空 node_modules 目录，重新 install 后再看看
2. 尝试找出冲突的插件并禁用，一般冲突插件是会修改链接的插件
3. 把插件顺序上调或则调至最后

**Comment by kumakumasan** [comment]
已经找到原因了，是因为我的文档内容里面没有H1内容，所以无法回到头部，我给每个文档增加了H1内容以后，回到头部的问题就解决了。多谢。
