### ISSUE TITLE
请问下如何让pageTop和float样式的目录同时显示？

### ISSUE THREAD

**Issue by Cyndice** [zq99299/gitbook-plugin-anchor-navigation-ex#45]
请问下如何让pageTop和float样式的目录同时显示？

Thanks!

**Comment by zq99299** [comment]
有点忘记了，你看看这个配置是不是你要的
[在页面中增加`<extoc></extoc>` 标签，会在此处生成TOC目录](https://github.com/zq99299/gitbook-plugin-anchor-navigation-ex/blob/master/doc/config.md#%E9%A2%9D%E5%A4%96%E5%8A%9F%E8%83%BD%E6%94%AF%E6%8C%81)

**Comment by Cyndice** [comment]
> 有点忘记了，你看看这个配置是不是你要的 [在页面中增加`<extoc></extoc>` 标签，会在此处生成TOC目录](https://github.com/zq99299/gitbook-plugin-anchor-navigation-ex/blob/master/doc/config.md#%E9%A2%9D%E5%A4%96%E5%8A%9F%E8%83%BD%E6%94%AF%E6%8C%81)

可以实现，非常感谢！
